version: '3.8'

services:
  mysql_db:
    container_name: mysql_db
    restart: always
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    env_file:
      - .development.env
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
volumes:
  db-config:
  db-data: